# Generated by Django 4.1 on 2022-11-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang_name", models.CharField(max_length=200)),
                ("lang_text", models.TextField(blank=True, null=True)),
                ("lang_img", models.ImageField(upload_to="media/images/poster")),
                ("lang_initial", models.CharField(max_length=200)),
            ],
        ),
    ]
