# Generated by Django 4.1 on 2022-11-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignDonate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang_name", models.CharField(max_length=200)),
                ("lang_text", models.TextField(max_length=200)),
                ("donate_video", models.FileField(upload_to="media/video")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
